add step to check status of started job

diff --git a/.github/workflows/google.yml b/.github/workflows/google.yml
--- a/.github/workflows/google.yml
+++ b/.github/workflows/google.yml
@@ -74,11 +74,23 @@ jobs:
               --format="get(job.id)")
 
       - name: Wait for job start
+        id: wait-job-start
         if: steps.start-job.outputs.job-id != ''
         run: |-
           function get_status() {
             echo "$(gcloud dataflow jobs show '${{ steps.start-job.outputs.job-id }}' --region=$REGION --format='get(state)')"
           }
-          while [[ "$(get_status)" == 'Queued' || "$(get_status)" == 'Starting' ]]; do
+          while [[ "$(get_status)" == "Queued" || "$(get_status)" == "Starting" ]]; do
             sleep 10s
           done
+          echo ::set-output name=job-status::"$(get_status)"
+
+      - name: Check started job status
+        run: |-
+          if [[ "${{ steps.wait-job-start.outputs.job-status }}" != "Running" ]]
+          then
+            echo "Failed to start a job."
+            exit 1
+          else
+            echo "Job with id '${{ steps.start-job.outputs.job-id }}' has been successfully started."
+          fi
